version: '3.8'
services:
  postgres:
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: twinn
      POSTGRES_PASSWORD: twinnpassword
      POSTGRES_DB: twinndb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 