import { Drop, Collection } from "./types";

export const POAPDummyData: Drop[] = [
  {
    image: "/logo.svg",
    numberOfCollectors: 1,
    id: "189771",
    title: "Twinn Platform Launch",
    date: "May 6, 2023",
    location: "Virtual",
    isNew: true,
    isFeatured: true,
    description:
      "This is your proof of being there when it all started. Thanks for joining our launch party and helping us kick off the Twinn journey on Solana. Here's to many more memories on-chain!",
    supply: 1250,
    power: 12500,
    moments: 24,
    transfers: 87,
    collectionId: "3",
    collectors: [
      {
        wallet: "twinn.sol",
        network: "Solana",
        mintedTime: "about 17 hours ago",
        power: 150,
      },
    ],
  },
  {
    image: "/dummy/breakpoint.png",
    numberOfCollectors: 27,
    id: "189672",
    title: "Breakpoint Dubai 2023",
    date: "Nov 15 - 17, 2023",
    location: "Dubai, UAE",
    isNew: true,
    isFeatured: true,
    description:
      "You made it to Breakpoint Dubai! This memento captures the energy of those three days where we talked, coded, and dreamed about the future of Solana. From keynotes to late-night hacks - thanks for being part of the magic.",
    artistInfo: "4uockXKuNbtNvayaJp5czTDSj5PeF5ssaYFLxVziRzBx",
    supply: 2800,
    power: 28000,
    moments: 0,
    transfers: 0,
    collectionId: "1",
    externalLink: "breakpoint.solana.com",
    collectors: [
      {
        wallet: "4uockXKuNbtNvayaJp5czTDSj5PeF5ssaYFLxVziRzBx",
        network: "Solana",
        mintedTime: "about 1 minute ago",
        power: 10,
      },
    ],
    mints: 1,
    reservations: 0,
  },
  {
    image: "/dummy/solana.png",
    numberOfCollectors: 1820,
    id: "123457",
    title: "Saga Phone Launch",
    date: "Jun 23, 2022",
    location: "New York, NY",
    isNew: false,
    isFeatured: false,
    description:
      "Remember when Solana dropped a phone on us? This is your proof of being there when the Saga was first revealed. Web3 in your pocket - we're still not over it.",
    supply: 1825,
    power: 18250,
    moments: 32,
    transfers: 215,
    collectionId: "1",
    collectors: [
      {
        wallet: "anatoly.sol",
        network: "Solana",
        mintedTime: "41 minutes ago",
        power: 500,
      },
      {
        wallet: "raj.sol",
        network: "Solana",
        mintedTime: "about 2 hours ago",
        power: 320,
      },
      {
        wallet: "armani.sol",
        network: "Solana",
        mintedTime: "about 3 hours ago",
        power: 280,
      },
      {
        wallet: "vibhu.sol",
        network: "Solana",
        mintedTime: "about 3 hours ago",
        power: 250,
      },
      {
        wallet: "austin.sol",
        network: "Solana",
        mintedTime: "about 4 hours ago",
        power: 220,
      },
      {
        wallet: "mert.sol",
        network: "Solana",
        mintedTime: "about 5 hours ago",
        power: 190,
      },
      {
        wallet: "clay.sol",
        network: "Solana",
        mintedTime: "about 5 hours ago",
        power: 175,
      },
      {
        wallet: "jordan.sol",
        network: "Solana",
        mintedTime: "about 6 hours ago",
        power: 160,
      },
      {
        wallet: "hana.sol",
        network: "Solana",
        mintedTime: "about 7 hours ago",
        power: 145,
      },
      {
        wallet: "dylan.sol",
        network: "Solana",
        mintedTime: "about 8 hours ago",
        power: 130,
      },
      {
        wallet: "toly.sol",
        network: "Solana",
        mintedTime: "about 8 hours ago",
        power: 120,
      },
      {
        wallet: "yakovenko.sol",
        network: "Solana",
        mintedTime: "about 9 hours ago",
        power: 110,
      },
      {
        wallet: "solana.sol",
        network: "Solana",
        mintedTime: "about 10 hours ago",
        power: 100,
      },
    ],
  },
];

export const CollectionsDummyData: Collection[] = [
  {
    id: "1",
    name: "Solana Foundation",
    description: "The good stuff from official Solana events",
    coverImage: "/dummy/solana-cover.png",
    image: "/dummy/solana.png",
    creator: { id: "solana.sol", name: "Solana Foundation" },
    dropCount: 2,
    collectorsCount: 4601,
    isVerified: true,
    createdAt: "January 10, 2024",
    type: "Organization",
  },
  {
    id: "2",
    name: "Superteam",
    description: "Collectibles from the Superteam community",
    coverImage: "/dummy/superteam-cover.png",
    image: "/dummy/superteam.png",
    creator: { id: "superteam.sol", name: "Superteam" },
    dropCount: 0,
    collectorsCount: 2150,
    isVerified: true,
    createdAt: "March 15, 2024",
    type: "Organization",
  },
  {
    id: "3",
    name: "Twinn",
    description: "Our drops. Our memories. Welcome home.",
    coverImage: "/dummy/twinn-cover.png",
    image: "/logo.svg",
    creator: { id: "twinn.sol", name: "Twinn" },
    dropCount: 1,
    collectorsCount: 1253,
    isVerified: true,
    createdAt: "February 22, 2024",
    type: "Organization",
  },
  {
    id: "4",
    name: "Magic Eden",
    description: "Marketplace magic from the ME team",
    coverImage: "/dummy/magiceden-cover.png",
    image: "/dummy/magiceden.png",
    creator: { id: "magiceden.sol", name: "Magic Eden" },
    dropCount: 0,
    collectorsCount: 3250,
    isVerified: true,
    createdAt: "June 5, 2024",
    type: "Organization",
  },
  {
    id: "5",
    name: "Hacker Houses",
    description: "Been to a Solana Hacker House? Prove it.",
    coverImage: "/dummy/hackerhouse-cover.png",
    image: "/dummy/hackerhouse.png",
    creator: { id: "solana.sol", name: "Solana Foundation" },
    dropCount: 1,
    collectorsCount: 945,
    isVerified: true,
    createdAt: "February 8, 2025",
    type: "Organization",
  },
];
